import { Character, Stage, ActionType } from "../types";

// This service simulates fetching "static" assets generated by Nano Banana.
// In a real build, these would be paths to .png/.jpg files in the public folder.
// Here, we generate high-quality SVG manga panels on the fly to represent those static files.

const MANGA_FONTS = 'font-family="Courier New, monospace" font-weight="900"';

/**
 * Generates a static SVG data URI representing a Manga panel for a specific game state.
 */
export const generatePanelImage = async (
  p1: Character,
  p2: Character,
  stage: Stage,
  description: string,
  p1Action: ActionType,
  p2Action: ActionType
): Promise<string> => {
  
  // Determine the visual "theme" of the panel based on interactions
  let panelType: 'CLASH' | 'HIT_P1' | 'HIT_P2' | 'BLOCK' | 'MOVE' | 'SKILL' = 'MOVE';
  let mainText = "WOOSH";
  let subText = "";
  
  // Simple logic to pick the "file"
  if (p1Action === ActionType.SKILL || p2Action === ActionType.SKILL) {
    panelType = 'SKILL';
    mainText = p1Action === ActionType.SKILL ? p1.skillName.toUpperCase() : p2.skillName.toUpperCase();
  } else if (p1Action === ActionType.ATTACK && p2Action === ActionType.ATTACK) {
    panelType = 'CLASH';
    mainText = "CLASH!!";
  } else if (p1Action === ActionType.ATTACK && p2Action !== ActionType.BLOCK) {
    panelType = 'HIT_P2';
    mainText = "SMASH!";
    subText = "POW";
  } else if (p2Action === ActionType.ATTACK && p1Action !== ActionType.BLOCK) {
    panelType = 'HIT_P1';
    mainText = "CRUSH!";
    subText = "BAM";
  } else if ((p1Action === ActionType.ATTACK && p2Action === ActionType.BLOCK) || (p2Action === ActionType.ATTACK && p1Action === ActionType.BLOCK)) {
    panelType = 'BLOCK';
    mainText = "KANG!";
  } else if (p1Action === ActionType.JUMP || p2Action === ActionType.JUMP) {
    panelType = 'MOVE';
    mainText = "JUMP!";
  } else {
    panelType = 'MOVE';
    mainText = "...";
  }

  // SVG Construction
  const width = 600;
  const height = 600;
  
  let bgPattern = '';
  let fgElements = '';

  // Backgrounds (Simulating Halftones/Speedlines)
  if (panelType === 'SKILL') {
    // Inverted Impact
    bgPattern = `
      <rect width="100%" height="100%" fill="black"/>
      <circle cx="300" cy="300" r="250" fill="white" opacity="0.1"/>
      <path d="M300 0 L350 300 L300 600 L250 300 Z" fill="white" opacity="0.5"/>
      <path d="M0 300 L300 350 L600 300 L300 250 Z" fill="white" opacity="0.5"/>
    `;
  } else if (panelType === 'CLASH' || panelType === 'HIT_P1' || panelType === 'HIT_P2') {
    // Radical Speed lines
    bgPattern = `
      <rect width="100%" height="100%" fill="white"/>
      <defs>
        <radialGradient id="grad1" cx="50%" cy="50%" r="50%" fx="50%" fy="50%">
          <stop offset="0%" style="stop-color:white;stop-opacity:1" />
          <stop offset="100%" style="stop-color:black;stop-opacity:1" />
        </radialGradient>
      </defs>
      <circle cx="300" cy="300" r="400" fill="url(#grad1)" opacity="0.2"/>
      ${Array.from({length: 40}).map((_, i) => {
        const rot = i * 9;
        return `<rect x="300" y="300" width="600" height="5" transform="rotate(${rot} 300 300) translate(50 0)" fill="black" />`;
      }).join('')}
      <circle cx="300" cy="300" r="200" fill="white"/>
    `;
  } else {
    // Horizontal speed lines for movement
    bgPattern = `
      <rect width="100%" height="100%" fill="white"/>
      ${Array.from({length: 20}).map((_, i) => 
        `<rect x="0" y="${i * 30}" width="600" height="2" fill="black" opacity="0.3"/>`
      ).join('')}
    `;
  }

  // Foreground Text & Shapes (Simulating Action)
  const textStyle = `${MANGA_FONTS} font-size="80" fill="none" stroke="black" stroke-width="4" paint-order="stroke"`;
  const textFill = `fill="${panelType === 'SKILL' ? 'white' : 'black'}"`;
  
  fgElements = `
    <text x="50%" y="50%" dominant-baseline="middle" text-anchor="middle" ${textStyle} stroke="white" stroke-width="15">${mainText}</text>
    <text x="50%" y="50%" dominant-baseline="middle" text-anchor="middle" ${textStyle}>${mainText}</text>
    <text x="50%" y="50%" dominant-baseline="middle" text-anchor="middle" ${MANGA_FONTS} font-size="80" ${textFill}>${mainText}</text>
  `;

  if (subText) {
    fgElements += `
       <text x="80%" y="80%" transform="rotate(-15 480 480)" ${MANGA_FONTS} font-size="60" fill="red" stroke="white" stroke-width="5">${subText}</text>
    `;
  }

  // Combine into SVG
  const svgString = `
    <svg width="${width}" height="${height}" xmlns="http://www.w3.org/2000/svg">
      ${bgPattern}
      ${fgElements}
      <rect width="100%" height="100%" fill="none" stroke="black" stroke-width="20"/>
    </svg>
  `;

  // Encode to Base64
  return `data:image/svg+xml;base64,${btoa(svgString)}`;
};